"""BotManagerPort — domain protocol for bot lifecycle operations needed by Telegram."""

from __future__ import annotations

from decimal import Decimal
from typing import Any, Protocol


class BotManagerPort(Protocol):
    """Protocol defining the bot lifecycle methods used by HandleTelegramCommand.

    Both the real BotManager and test fakes implement this interface.
    Using a Protocol rather than ABC+inheritance keeps BotManager unaware
    of the Telegram use case's specific needs.
    """

    def is_running(self) -> bool: ...

    def get_status(self) -> dict[str, object]: ...

    def start(
        self,
        strategy_path: str,
        symbol: str,
        interval: str,
        mode: str,
        warmup_bars: int = 100,
        live_trading_ack: bool = False,
    ) -> dict[str, str]: ...

    def stop(self) -> dict[str, str]: ...

    def list_bot_runs(
        self, limit: int = 20, mode_filter: str | None = None
    ) -> list[Any]: ...

    def cancel_all_orders(self, symbol: str) -> dict[str, object]: ...

    def close_position(self, symbol: str) -> dict[str, object]: ...

    # -- trading-control spec (manual orders, leverage, config, risk orders) --

    def activate_symbol(self, symbol: str) -> dict[str, str]: ...

    def get_active_symbol(self) -> Any: ...

    def get_active_price(self) -> Decimal | None: ...

    def get_active_position(self) -> Any: ...

    def get_balance(self) -> Any: ...

    def set_leverage(self, leverage: int, margin_mode: str = "isolated") -> dict[str, str]: ...

    def submit_manual_order(self, side: Any, size: Decimal) -> dict[str, Any]: ...

    def close_active_position(self) -> dict[str, str]: ...

    def clear_all(self) -> dict[str, Any]: ...

    def attach_stop_loss(self, price: Decimal) -> dict[str, Any]: ...

    def attach_take_profit(self, price: Decimal) -> dict[str, Any]: ...

    def clear_risk_order(self, kind: str) -> dict[str, Any]: ...

    def list_active_orders(self) -> list[dict[str, Any]] | None: ...

    def cancel_order(self, order_id: str) -> dict[str, Any]: ...

    def save_config_profile(self, name: str) -> dict[str, Any]: ...

    def load_config_profile(self, name: str) -> dict[str, Any]: ...

    def list_config_profiles(self) -> dict[str, Any]: ...

    def get_bot_config(self) -> Any: ...

    def update_bot_config(self, key: str, value: str) -> dict[str, str]: ...

    def set_default_size(self, size: Decimal) -> dict[str, str]: ...

    def get_default_size(self) -> Decimal | None: ...

    def clear_default_size(self) -> None: ...
